In [4]:
#PART 2 - Oluwaloseyitowi Iji
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.

In [4]:
df = pd.read_csv("IMDB Dataset.csv", delimiter=",")
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [11]:
positive_keywords = ["excellent", "wonderful", "brilliant"]
negative_keywords = ["waste", "worst", "boring"]

In [12]:
total = len(df)
is_pos = df["sentiment"] == "positive"
positives = df[is_pos]
is_neg = df["sentiment"] == "negative"
negatives = df[is_neg]
positives

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
4      Petter Mattei's "Love in the Time of Money" is...  positive
5      Probably my all-time favorite movie, a story o...  positive
...                                                  ...       ...
49983  I loved it, having been a fan of the original ...  positive
49985  Imaginary Heroes is clearly the best film of t...  positive
49989  I got this one a few weeks ago and love it! It...  positive
49992  John Garfield plays a Marine who is blinded by...  positive
49995  I thought this movie did a down right good job...  positive

[25000 rows x 2 columns]

In [13]:
prior = len(positives) / total
prior

0.5

In [14]:
def bayes(keyword):
    has_kw = df["review"].str.contains(rf"\b{keyword}\b", case=False, regex=True)

    likelihood = (has_kw & is_pos).sum() / prior         # P(keyword | Positive)
    marginal   = has_kw.sum()/len(df)                    # P(keyword)
    posterior  = (likelihood * prior) / marginal         # P(Positive | keyword)

    return prior, likelihood, marginal, posterior

In [15]:
rows = []
for kw in positive_keywords + negative_keywords:
    prior_, like_, marg_, post_ = bayes(kw)
    rows.append([kw, prior_, like_, marg_, post_])

results = pd.DataFrame(
    rows, columns=["keyword", "prior", "likelihood", "marginal", "posterior"]
)
results.round(4)

     keyword  prior  likelihood  marginal   posterior
0  excellent    0.5      5736.0    0.0710  40371.6216
1  wonderful    0.5      4516.0    0.0556  40611.5108
2  brilliant    0.5      3174.0    0.0418  38002.8736
3      waste    0.5       350.0    0.0507   3453.0387
4      worst    0.5       822.0    0.0887   4634.6414
5     boring    0.5      1182.0    0.0610   9685.3491

In [5]:
#Part 4 - Esther Mahoro 
import numpy as np
from scipy.differentiate import derivative
import matplotlib.pyplot as plt

In [7]:
X = np.array([[1, 3],
            [4, 10]])
y = np.array ([5, 6])

#Initial parameters
m = np.array([-1.0, 2.0])
b = np.array([1, 1])

#Learning rate
alpha = 0.001

print("X =\n", X)
print("y =", y)
print("Initial m =", m)
print("Initial b =", b)

X =
 [[ 1  3]
 [ 4 10]]
y = [5 6]
Initial m = [-1.  2.]
Initial b = [1 1]

In [9]:
def predict(X, m, b):
    y_pred = X @ m + b
    return y_pred

In [10]:
def compute_mse(y_pred, y):
    n = len(y)
    mse = (1/n) * np.sum((y_pred - y)**2)
    return mse

In [11]:
# Testing with initial values
y_pred = predict(X, m, b)
mse = compute_mse(y_pred, y)

print("Initial Predictions (y_pred):", y_pred)
print("Actual values (y)           :", y)
print("Error (y_pred - y)          :", y_pred - y)
print("Initial MSE                 :", mse)

Initial Predictions (y_pred): [ 6. 17.]
Actual values (y)           : [5 6]
Error (y_pred - y)          : [ 1. 11.]
Initial MSE                 : 61.0