In [2]:
#PART 2 - Oluwaloseyitowi Iji
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("IMDB Dataset.csv", delimiter=",")
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
positive_keywords = ["excellent", "wonderful", "brilliant"]
negative_keywords = ["waste", "worst", "boring"]

In [5]:
total = len(df)
is_pos = df["sentiment"] == "positive"
positives = df[is_pos]
is_neg = df["sentiment"] == "negative"
negatives = df[is_neg]
positives

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
4      Petter Mattei's "Love in the Time of Money" is...  positive
5      Probably my all-time favorite movie, a story o...  positive
...                                                  ...       ...
49983  I loved it, having been a fan of the original ...  positive
49985  Imaginary Heroes is clearly the best film of t...  positive
49989  I got this one a few weeks ago and love it! It...  positive
49992  John Garfield plays a Marine who is blinded by...  positive
49995  I thought this movie did a down right good job...  positive

[25000 rows x 2 columns]

In [6]:
prior = len(positives) / total
prior

0.5

In [7]:
def bayes(keyword):
    has_kw = df["review"].str.contains(rf"\b{keyword}\b", case=False, regex=True)

    likelihood = (has_kw & is_pos).sum() / prior         # P(keyword | Positive)
    marginal   = has_kw.sum()/len(df)                    # P(keyword)
    posterior  = (likelihood * prior) / marginal         # P(Positive | keyword)

    return prior, likelihood, marginal, posterior